version: '5'
services:
  api-solid-pg:
    image: bitnami/postgresql:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
